### ISSUE TITLE
Issues with GitHub PAT token

### ISSUE THREAD

**Issue by asos-javierdorigoni** [thomhurst/PullRequestScanner#7]
Hi @thomhurst we are experimenting issues while re-deploying our Azure Function that uses this library. Basically having a full permission Personal Access Token for GitHub still does not perform the right query to retrieve the Team Members of the organization. 
Does the PAT token requires a very specific permission? The Azure DevOps plugin integration works well though.
If you are free you can always reach out to me on javier.dorigoni@asos.com for a short sync.

**Comment by thomhurst** [comment]
> Hi @thomhurst we are experimenting issues while re-deploying our Azure Function that uses this library. Basically having a full permission Personal Access Token for GitHub still does not perform the right query to retrieve the Team Members of the organization. Does the PAT token requires a very specific permission? The Azure DevOps plugin integration works well though. If you are free you can always reach out to me on [javier.dorigoni@asos.com](mailto:javier.dorigoni@asos.com) for a short sync.

Afaik the permissions shouldn't result in a different query. But when I set it up originally I did always use the least access required.

What are you seeing Vs what are you expecting?

**Comment by asos-javierdorigoni** [comment]
![image](https://github.com/thomhurst/PullRequestScanner/assets/88502431/1c386cd0-ca4b-4c9b-80fb-83bb15a2913f)
Basically the GraphQL query returns a null object when requesting the GetTeamMembers()

**Comment by thomhurst** [comment]
@asos-javierdorigoni if I put out a beta version later could you test it?

**Comment by asos-javierdorigoni** [comment]
Yes of course

**Comment by thomhurst** [comment]
@asos-javierdorigoni Do you wanna try this package version? 3.0.4-PullRequest0009-12

**Comment by thomhurst** [comment]
@asos-javierdorigoni v3.2.0 is now on NuGet.
